namespace Editor
{
    public enum CommandType
    {
        None,
        Text,
        ShowBox,
        HideBox,
        SquareRoot,
        NRoot,
        Division,
        LeftBracket,
        RightBracket,
        LeftRightBracket,
        Sub,
        Super,
        SubAndSuper,
        SignComposite,
        Composite,
        CompositeBig,
        TopBracket,
        BottomBracket,
        DoubleArrowBarBracket,
        Decorated,
        Arrow,
        Box,
        Matrix,
        CustomMatrix,
        DecoratedCharacter
    }
}